--------------------------------------------------------
--  File created - Tuesday-January-02-2024   
--------------------------------------------------------
DROP SEQUENCE "PP_ADMIN"."PP_APPLICATIONNOTE_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_APPLICATION_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_AUDIT_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_BNOTE_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_BOOKING_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_LOG_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_MEMBER_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_NOTFIC_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_OFFER_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_RECOMMENDATION_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_SCHEDULE_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_SLOT_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_STAT_SEQ";
DROP SEQUENCE "PP_ADMIN"."PP_TRANSCRIPT_SEQ";
DROP TABLE "PP_ADMIN"."PP_APPLICATION" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_APPLICATIONSTATUS" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_AUDIT" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_BOOKING" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_BOOKINGNOTE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_BOOKINGSTATUS" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_BOOKINGTYPE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_COURSE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_DAY" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_LOG" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_METADATA" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_NOTIFICATION" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_OFFEREDCOURSE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_RECOMMENDATION" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_RECSTATUS" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_ROLE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_SCHEDULE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_SCHOOL" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_SLOT" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_SLOTTYPE" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_STATISTIC" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_TRANSCRIPT" cascade constraints;
DROP TABLE "PP_ADMIN"."PP_USER" cascade constraints;
DROP PROCEDURE "PP_ADMIN"."FETCH_STATS";
--------------------------------------------------------
--  DDL for Sequence PP_APPLICATIONNOTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_APPLICATIONNOTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_APPLICATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_APPLICATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_AUDIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_AUDIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_BNOTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_BNOTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_BOOKING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_BOOKING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_MEMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_MEMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_NOTFIC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_NOTFIC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_OFFER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_OFFER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_RECOMMENDATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_RECOMMENDATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_SCHEDULE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_SCHEDULE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_SLOT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_SLOT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_STAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_STAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PP_TRANSCRIPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PP_ADMIN"."PP_TRANSCRIPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table PP_APPLICATION
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_APPLICATION" 
   (	"APPLICATIONID" NUMBER, 
	"DATETIME" TIMESTAMP (6), 
	"NOTE" NVARCHAR2(1000), 
	"APLCSTATUSID" CHAR(1 CHAR), 
	"STUDENTID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_APPLICATIONNOTE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" 
   (	"NOTEID" NUMBER, 
	"DATETIME" TIMESTAMP (6), 
	"NOTEBODY" NVARCHAR2(1000), 
	"APPLICATIONID" NUMBER, 
	"USERID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_APPLICATIONSTATUS
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_APPLICATIONSTATUS" 
   (	"STATUSID" CHAR(1 BYTE), 
	"STATUSNAME" NVARCHAR2(50), 
	"STATUSDESC" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_AUDIT
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_AUDIT" 
   (	"AUDITID" NUMBER, 
	"CHANGETYPE" CHAR(1 CHAR), 
	"ENTITYNAME" NVARCHAR2(50), 
	"DATETIME" TIMESTAMP (6), 
	"OLDVALUE" BLOB, 
	"NEWVALUE" BLOB, 
	"USERID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("OLDVALUE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NEWVALUE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "PP_ADMIN"."PP_AUDIT"  IS 'TO SAVE CRUD OPERATIONS (FOR SENSTIVE OPERATIONS ONLY) LOGS';
--------------------------------------------------------
--  DDL for Table PP_BOOKING
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_BOOKING" 
   (	"BOOKINGID" NUMBER, 
	"DATEBOOKED" TIMESTAMP (6), 
	"BOOKINGDATE" DATE, 
	"NOTE" NVARCHAR2(1000), 
	"STARTTIME" TIMESTAMP (6), 
	"ENDTIME" TIMESTAMP (6), 
	"BOOKINGLIMIT" NUMBER, 
	"ISONLINE" NUMBER, 
	"SLOTID" NUMBER, 
	"STATUSID" CHAR(1 CHAR), 
	"STUDENTID" NVARCHAR2(50), 
	"COURSEID" NVARCHAR2(6), 
	"TYPEID" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_BOOKINGMEMBER
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" 
   (	"MEMBERID" NUMBER, 
	"DATETIME" TIMESTAMP (6), 
	"STUDENTID" NVARCHAR2(50), 
	"BOOKINGID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_BOOKINGNOTE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_BOOKINGNOTE" 
   (	"NOTEID" NUMBER, 
	"DATETIME" TIMESTAMP (6), 
	"NOTEBODY" NVARCHAR2(1000), 
	"BOOKINGID" NUMBER, 
	"USERID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_BOOKINGSTATUS
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_BOOKINGSTATUS" 
   (	"STATUSID" CHAR(1 CHAR), 
	"STATUSNAME" NVARCHAR2(50), 
	"STATUSDESC" NVARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_BOOKINGTYPE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_BOOKINGTYPE" 
   (	"TYPEID" CHAR(1 BYTE), 
	"TYPENAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_COURSE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_COURSE" 
   (	"COURSEID" NVARCHAR2(6), 
	"COURSENAME" NVARCHAR2(100), 
	"SCHOOLID" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_DAY
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_DAY" 
   (	"DAYID" CHAR(1 BYTE), 
	"DAYNAME" NVARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_DAY"  IS 'A LIST FOR DAYS OF THE WEEK';
--------------------------------------------------------
--  DDL for Table PP_LOG
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_LOG" 
   (	"LOGID" NUMBER, 
	"ERRORMSG" NVARCHAR2(1000), 
	"DATETIME" TIMESTAMP (6), 
	"USERID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_LOG"  IS 'TO SAVE ERRORS AND EXCEPTIONS WHICH MAY HAPPEN IN THE APP';
--------------------------------------------------------
--  DDL for Table PP_METADATA
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_METADATA" 
   (	"METADATAID" NUMBER, 
	"MRWSTART" DATE, 
	"MRWEND" DATE, 
	"MWSTART" DATE, 
	"MWEND" DATE, 
	"FRWSTART" DATE, 
	"FRWEND" DATE, 
	"FWSTART" DATE, 
	"FWEND" DATE, 
	"ENABLED" NUMBER(1,0), 
	"BOOKING" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_NOTIFICATION" 
   (	"NOTFICID" NUMBER, 
	"ENTITY" NVARCHAR2(50), 
	"ITEMID" NVARCHAR2(50), 
	"NOTFICMSG" NVARCHAR2(200), 
	"USERID" NVARCHAR2(50), 
	"SEEN" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_OFFEREDCOURSE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_OFFEREDCOURSE" 
   (	"OFFERID" NUMBER, 
	"LEADERID" NVARCHAR2(50), 
	"COURSEID" NVARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_OFFEREDCOURSE"  IS 'TO STORE COURSES WHICH PASS LEADERS ARE WILLING TO TEACH';
--------------------------------------------------------
--  DDL for Table PP_RECOMMENDATION
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_RECOMMENDATION" 
   (	"RECID" NUMBER, 
	"DATETIME" TIMESTAMP (6), 
	"NOTE" NVARCHAR2(1000), 
	"STATUSID" CHAR(1 BYTE), 
	"TUTORID" NVARCHAR2(50), 
	"STUDENTID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_RECOMMENDATION"  IS 'TO STORE TUTOR RECOMANDATIONS FOR STUDENTS';
--------------------------------------------------------
--  DDL for Table PP_RECSTATUS
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_RECSTATUS" 
   (	"STATUSID" CHAR(1 BYTE), 
	"STATUSNAME" NVARCHAR2(20), 
	"STATUSDESC" NVARCHAR2(150)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_ROLE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_ROLE" 
   (	"ROLEID" NUMBER, 
	"ROLENAME" NVARCHAR2(20), 
	"ROLEDESC" NVARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_SCHEDULE" 
   (	"SCHEDULEID" NUMBER, 
	"STARTTIME" TIMESTAMP (6), 
	"ENDTIME" TIMESTAMP (6), 
	"DAYID" CHAR(1 BYTE), 
	"USERID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_SCHEDULE"  IS 'TO STORE STUDENTS / LEADERS SCHEDULES (USED TO VALIDATE TIMES BEETWEEN BOOKINGS) - NONE FREE TIMES';
--------------------------------------------------------
--  DDL for Table PP_SCHOOL
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_SCHOOL" 
   (	"SCHOOLID" NVARCHAR2(20), 
	"SCHOOLNAME" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_SCHOOL"  IS 'WHICH AREA OF TEACHING (EDICT, BUSSNIS ETC)';
--------------------------------------------------------
--  DDL for Table PP_SLOT
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_SLOT" 
   (	"SLOTID" NUMBER, 
	"STARTTIME" TIMESTAMP (6), 
	"ENDTIME" TIMESTAMP (6), 
	"NOTE" NVARCHAR2(250), 
	"DAYID" CHAR(1 CHAR), 
	"TYPEID" CHAR(1 BYTE), 
	"LEADERID" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_SLOT"  IS 'TO SAVE SLOTS (DAYS AND TIMES) WHICH LEADERS CAN HAVE THAIR OWN CLASSES';
--------------------------------------------------------
--  DDL for Table PP_SLOTTYPE
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_SLOTTYPE" 
   (	"TYPEID" CHAR(1 BYTE), 
	"TYPENAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_STATISTIC
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_STATISTIC" 
   (	"STATID" NUMBER, 
	"STATDATE" DATE, 
	"STUDENTNO" NUMBER, 
	"LEADERNO" NUMBER, 
	"BKDSESSIONSNO" NUMBER, 
	"HOURSNO" NUMBER, 
	"ICT" NUMBER, 
	"BUSINESS" NUMBER, 
	"ENGINEERING" NUMBER, 
	"WEBMEDIA" NUMBER, 
	"VISUALDESIGN" NUMBER, 
	"LOGISTICS" NUMBER, 
	"OTHER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PP_TRANSCRIPT
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_TRANSCRIPT" 
   (	"TRANSID" NUMBER, 
	"GRADE" NVARCHAR2(2), 
	"STUDENTID" NVARCHAR2(50), 
	"COURSEID" NVARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_TRANSCRIPT"  IS 'TO SAVE LEADERS OR APPLICANTS TRANSCRIPT (USER FOR VALIDATING IF A LEADER CAN TEACH A SUBJECT)';
--------------------------------------------------------
--  DDL for Table PP_USER
--------------------------------------------------------

  CREATE TABLE "PP_ADMIN"."PP_USER" 
   (	"USERID" NVARCHAR2(50), 
	"ROLEID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "PP_ADMIN"."PP_USER"  IS 'THE MAIN TABLE WHICH USER INFO AND ROLE WILL BE SAVED (ONLY ID AND ROLE AS AUTHINTICATION AND INFO WILL BE RETRIVED SEPRATILY)';

REM INSERTING into PP_ADMIN.PP_APPLICATIONSTATUS
SET DEFINE OFF;
Insert into PP_ADMIN.PP_APPLICATIONSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('C','created','the request has been created by student');
Insert into PP_ADMIN.PP_APPLICATIONSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('R','reviewd','the application has been reviewd by the manager');
Insert into PP_ADMIN.PP_APPLICATIONSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('I','interview','the application is up for interview, please check notes');
Insert into PP_ADMIN.PP_APPLICATIONSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('A','accepted','appliaction accepted, welcome as a pass leader');
Insert into PP_ADMIN.PP_APPLICATIONSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('N','rejected','application rejected, try next semaster');
Insert into PP_ADMIN.PP_APPLICATIONSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('P','cancled','the application was cancled by the student');
Insert into PP_ADMIN.PP_APPLICATIONSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('T','reopened','the application has been reopened by the student');
REM INSERTING into PP_ADMIN.PP_BOOKINGSTATUS
SET DEFINE OFF;
Insert into PP_ADMIN.PP_BOOKINGSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('A','active','the booking has been created and is ongoing');
Insert into PP_ADMIN.PP_BOOKINGSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('F','finished','the booking has been complete and fully done by pass leader');
Insert into PP_ADMIN.PP_BOOKINGSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('C','cancelled','the booking has been cancelled by pass leader');
Insert into PP_ADMIN.PP_BOOKINGSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('S','student cancelled','the booking has been cancelled by booked student');
Insert into PP_ADMIN.PP_BOOKINGSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('R','rescheduled','the booking has been rescheduled by student to another booking');
Insert into PP_ADMIN.PP_BOOKINGSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('I','ignored','the booking was ghosted by the student');
REM INSERTING into PP_ADMIN.PP_BOOKINGTYPE
SET DEFINE OFF;
Insert into PP_ADMIN.PP_BOOKINGTYPE (TYPEID,TYPENAME) values ('N','normal');
Insert into PP_ADMIN.PP_BOOKINGTYPE (TYPEID,TYPENAME) values ('G','group');
Insert into PP_ADMIN.PP_BOOKINGTYPE (TYPEID,TYPENAME) values ('R','revision');
Insert into PP_ADMIN.PP_BOOKINGTYPE (TYPEID,TYPENAME) values ('U','unscheduled');
Insert into PP_ADMIN.PP_BOOKINGTYPE (TYPEID,TYPENAME) values ('Z','group unscheduled');
REM INSERTING into PP_ADMIN.PP_DAY
SET DEFINE OFF;
Insert into PP_ADMIN.PP_DAY (DAYID,DAYNAME) values ('U','Sunday');
Insert into PP_ADMIN.PP_DAY (DAYID,DAYNAME) values ('M','Monday');
Insert into PP_ADMIN.PP_DAY (DAYID,DAYNAME) values ('T','Tuesday');
Insert into PP_ADMIN.PP_DAY (DAYID,DAYNAME) values ('W','Wednesday');
Insert into PP_ADMIN.PP_DAY (DAYID,DAYNAME) values ('R','Thursday');
Insert into PP_ADMIN.PP_DAY (DAYID,DAYNAME) values ('F','Friday');
Insert into PP_ADMIN.PP_DAY (DAYID,DAYNAME) values ('S','Saturday');
SET DEFINE OFF;
Insert into PP_ADMIN.PP_RECSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('C','created','the request has been created by tutor');
Insert into PP_ADMIN.PP_RECSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('R','reviewed','the recommendation has been reviewd by the manager');
Insert into PP_ADMIN.PP_RECSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('I','interviewed','the recommendation is up for interview, please check notes');
Insert into PP_ADMIN.PP_RECSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('A','accepted','recommendation accepted, welcome as a pass leader');
Insert into PP_ADMIN.PP_RECSTATUS (STATUSID,STATUSNAME,STATUSDESC) values ('N','rejected','recommendation rejected, try next semaster');
REM INSERTING into PP_ADMIN.PP_ROLE
SET DEFINE OFF;
Insert into PP_ADMIN.PP_ROLE (ROLEID,ROLENAME,ROLEDESC) values (1,'student','can view and book session with leaders');
Insert into PP_ADMIN.PP_ROLE (ROLEID,ROLENAME,ROLEDESC) values (2,'leader','view, book, edit, add bookings, manage their own schdules and slots');
Insert into PP_ADMIN.PP_ROLE (ROLEID,ROLENAME,ROLEDESC) values (3,'tutor','can export lists of leaders and recommend students');
Insert into PP_ADMIN.PP_ROLE (ROLEID,ROLENAME,ROLEDESC) values (4,'manager','can have full control and reset system for new sem');
Insert into PP_ADMIN.PP_ROLE (ROLEID,ROLENAME,ROLEDESC) values (5,'admin','full control and log plus audits ');
REM INSERTING into PP_ADMIN.PP_SLOTTYPE
SET DEFINE OFF;
Insert into PP_ADMIN.PP_SLOTTYPE (TYPEID,TYPENAME) values ('O','online');
Insert into PP_ADMIN.PP_SLOTTYPE (TYPEID,TYPENAME) values ('P','physical');
Insert into PP_ADMIN.PP_SLOTTYPE (TYPEID,TYPENAME) values ('B','both');
Insert into PP_ADMIN.PP_SLOTTYPE (TYPEID,TYPENAME) values ('U','unscheduled');

--------------------------------------------------------
--  DDL for Index PK_AUDIT_AUDITID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_AUDIT_AUDITID" ON "PP_ADMIN"."PP_AUDIT" ("AUDITID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PP_BOOKINGTYPE_TYPEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_PP_BOOKINGTYPE_TYPEID" ON "PP_ADMIN"."PP_BOOKINGTYPE" ("TYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOG_LOGID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_LOG_LOGID" ON "PP_ADMIN"."PP_LOG" ("LOGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCHEDULE_SCHEDULEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_SCHEDULE_SCHEDULEID" ON "PP_ADMIN"."PP_SCHEDULE" ("SCHEDULEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROLE_ROLEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_ROLE_ROLEID" ON "PP_ADMIN"."PP_ROLE" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_OFFEREDCOURSE_OFFERID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_OFFEREDCOURSE_OFFERID" ON "PP_ADMIN"."PP_OFFEREDCOURSE" ("OFFERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOOKINGSTATUS_STATUSID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_BOOKINGSTATUS_STATUSID" ON "PP_ADMIN"."PP_BOOKINGSTATUS" ("STATUSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRANSCRIPT_TRANSID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_TRANSCRIPT_TRANSID" ON "PP_ADMIN"."PP_TRANSCRIPT" ("TRANSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOOKINGMEMBER_NOTEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_BOOKINGMEMBER_NOTEID" ON "PP_ADMIN"."PP_BOOKINGMEMBER" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_COURSE_COURSEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_COURSE_COURSEID" ON "PP_ADMIN"."PP_COURSE" ("COURSEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPLICATIONSTATUS_STATUSID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_APPLICATIONSTATUS_STATUSID" ON "PP_ADMIN"."PP_APPLICATIONSTATUS" ("STATUSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PP_NOTIFICATION_NOTEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_PP_NOTIFICATION_NOTEID" ON "PP_ADMIN"."PP_NOTIFICATION" ("NOTFICID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCHOOL_SCHOOLID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_SCHOOL_SCHOOLID" ON "PP_ADMIN"."PP_SCHOOL" ("SCHOOLID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DAY_DAYID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_DAY_DAYID" ON "PP_ADMIN"."PP_DAY" ("DAYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPLICATIONNOTE_NOTEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_APPLICATIONNOTE_NOTEID" ON "PP_ADMIN"."PP_APPLICATIONNOTE" ("NOTEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPLICATION_APPLICATIONID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_APPLICATION_APPLICATIONID" ON "PP_ADMIN"."PP_APPLICATION" ("APPLICATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SLOT_SLOTID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_SLOT_SLOTID" ON "PP_ADMIN"."PP_SLOT" ("SLOTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USER_USERID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_USER_USERID" ON "PP_ADMIN"."PP_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STATS_STATID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_STATS_STATID" ON "PP_ADMIN"."PP_STATISTIC" ("STATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOOKING_BOOKINGID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_BOOKING_BOOKINGID" ON "PP_ADMIN"."PP_BOOKING" ("BOOKINGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PP_SLOTTYPE_SLTTYPEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_PP_SLOTTYPE_SLTTYPEID" ON "PP_ADMIN"."PP_SLOTTYPE" ("TYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOOKINGNOTE_NOTEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_BOOKINGNOTE_NOTEID" ON "PP_ADMIN"."PP_BOOKINGNOTE" ("NOTEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RECSTATUS_STATUSID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_RECSTATUS_STATUSID" ON "PP_ADMIN"."PP_RECSTATUS" ("STATUSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RECOMMENDATION_RECID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_RECOMMENDATION_RECID" ON "PP_ADMIN"."PP_RECOMMENDATION" ("RECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PP_METADATA_METADAID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PP_ADMIN"."PK_PP_METADATA_METADAID" ON "PP_ADMIN"."PP_METADATA" ("METADATAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure FETCH_STATS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PP_ADMIN"."FETCH_STATS" AS
    studentNo NUMBER := 0;
    leaderNo NUMBER := 0;
    bkdNo NUMBER := 0;
    hrsNo NUMBER := 0;

    ict NUMBER := 0;
    bus NUMBER := 0;
    eng NUMBER := 0;
    web NUMBER := 0;
    vis NUMBER := 0;
    logt NUMBER := 0;
    othr NUMBER := 0;
BEGIN

    select count(*) into studentNo from pp_user WHERE roleid != 1;
    select count(*) into leaderNo from pp_user WHERE roleid = 2;
    select count(*) into bkdNo from pp_booking;
    SELECT CEIL(NVL(SUM((extract(day from (endtime - starttime)) * 24 * 60) + (extract(hour from (endtime - starttime)) * 60) + extract(minute from (endtime - starttime))) / 60, 0)) INTO hrsNo FROM pp_booking;

    select count(*) into ict from pp_booking where courseid LIKE 'IT%';
    select count(*) into bus from pp_booking where courseid LIKE 'BU%';
    select count(*) into eng from pp_booking where courseid LIKE 'EN%';
    select count(*) into web from pp_booking where courseid LIKE 'WM%';
    select count(*) into vis from pp_booking where courseid LIKE 'VC%';
    select count(*) into logt from pp_booking where courseid LIKE 'TL%';
    select count(*) into othr from pp_booking where courseid not LIKE 'IT%' and courseid not LIKE 'BU%' and courseid not LIKE 'EN%' and courseid not LIKE 'WM%' and courseid not LIKE 'VC%' and courseid not LIKE 'TL%';

    INSERt INTO pp_statistic VALUES (pp_stat_seq.nextval, SYSDATE, studentNo, leaderNo, bkdNo, hrsNo, ict, bus, eng, web, vis, logt, othr);

END;

/
--------------------------------------------------------
--  Constraints for Table PP_SCHOOL
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_SCHOOL" MODIFY ("SCHOOLNAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SCHOOL" ADD CONSTRAINT "PK_SCHOOL_SCHOOLID" PRIMARY KEY ("SCHOOLID")
  USING INDEX "PP_ADMIN"."PK_SCHOOL_SCHOOLID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_APPLICATIONNOTE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" MODIFY ("NOTEBODY" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" MODIFY ("APPLICATIONID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" ADD CONSTRAINT "PK_APPLICATIONNOTE_NOTEID" PRIMARY KEY ("NOTEID")
  USING INDEX "PP_ADMIN"."PK_APPLICATIONNOTE_NOTEID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_LOG
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_LOG" MODIFY ("ERRORMSG" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_LOG" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_LOG" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_LOG" ADD CONSTRAINT "PK_LOG_LOGID" PRIMARY KEY ("LOGID")
  USING INDEX "PP_ADMIN"."PK_LOG_LOGID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_RECOMMENDATION
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" MODIFY ("RECID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" MODIFY ("TUTORID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" ADD CONSTRAINT "PK_RECOMMENDATION_RECID" PRIMARY KEY ("RECID")
  USING INDEX "PP_ADMIN"."PK_RECOMMENDATION_RECID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_OFFEREDCOURSE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_OFFEREDCOURSE" MODIFY ("LEADERID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_OFFEREDCOURSE" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_OFFEREDCOURSE" ADD CONSTRAINT "PK_OFFEREDCOURSE_OFFERID" PRIMARY KEY ("OFFERID")
  USING INDEX "PP_ADMIN"."PK_OFFEREDCOURSE_OFFERID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_BOOKINGSTATUS
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKINGSTATUS" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGSTATUS" MODIFY ("STATUSNAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGSTATUS" MODIFY ("STATUSDESC" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGSTATUS" ADD CONSTRAINT "PK_BOOKINGSTATUS_STATUSID" PRIMARY KEY ("STATUSID")
  USING INDEX "PP_ADMIN"."PK_BOOKINGSTATUS_STATUSID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_BOOKINGNOTE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKINGNOTE" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGNOTE" MODIFY ("NOTEBODY" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGNOTE" MODIFY ("BOOKINGID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGNOTE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGNOTE" ADD CONSTRAINT "PK_BOOKINGNOTE_NOTEID" PRIMARY KEY ("NOTEID")
  USING INDEX "PP_ADMIN"."PK_BOOKINGNOTE_NOTEID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_ROLE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_ROLE" ADD CONSTRAINT "PK_ROLE_ROLEID" PRIMARY KEY ("ROLEID")
  USING INDEX "PP_ADMIN"."PK_ROLE_ROLEID"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_ROLE" MODIFY ("ROLENAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_ROLE" MODIFY ("ROLEDESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_BOOKINGMEMBER
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" MODIFY ("BOOKINGID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" ADD CONSTRAINT "PK_BOOKINGMEMBER_NOTEID" PRIMARY KEY ("MEMBERID")
  USING INDEX "PP_ADMIN"."PK_BOOKINGMEMBER_NOTEID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_METADATA
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_METADATA" ADD CONSTRAINT "PK_PP_METADATA_METADAID" PRIMARY KEY ("METADATAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("MRWSTART" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("MRWEND" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("MWSTART" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("MWEND" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("FRWSTART" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("FRWEND" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("FWSTART" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("FWEND" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_METADATA" MODIFY ("BOOKING" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" MODIFY ("SCHEDULEID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" MODIFY ("ENDTIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" MODIFY ("DAYID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE_SCHEDULEID" PRIMARY KEY ("SCHEDULEID")
  USING INDEX "PP_ADMIN"."PK_SCHEDULE_SCHEDULEID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_RECSTATUS
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_RECSTATUS" MODIFY ("STATUSNAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_RECSTATUS" MODIFY ("STATUSDESC" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_RECSTATUS" ADD CONSTRAINT "PK_RECSTATUS_STATUSID" PRIMARY KEY ("STATUSID")
  USING INDEX "PP_ADMIN"."PK_RECSTATUS_STATUSID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_DAY
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_DAY" MODIFY ("DAYID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_DAY" MODIFY ("DAYNAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_DAY" ADD CONSTRAINT "PK_DAY_DAYID" PRIMARY KEY ("DAYID")
  USING INDEX "PP_ADMIN"."PK_DAY_DAYID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_TRANSCRIPT
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_TRANSCRIPT" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_TRANSCRIPT" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_TRANSCRIPT" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_TRANSCRIPT" ADD CONSTRAINT "PK_TRANSCRIPT_TRANSID" PRIMARY KEY ("TRANSID")
  USING INDEX "PP_ADMIN"."PK_TRANSCRIPT_TRANSID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_BOOKINGTYPE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKINGTYPE" MODIFY ("TYPENAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGTYPE" ADD CONSTRAINT "PK_PP_BOOKINGTYPE_TYPEID" PRIMARY KEY ("TYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_SLOTTYPE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_SLOTTYPE" ADD CONSTRAINT "PK_PP_SLOTTYPE_SLTTYPEID" PRIMARY KEY ("TYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_SLOTTYPE" MODIFY ("TYPENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_COURSE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_COURSE" ADD CONSTRAINT "PK_COURSE_COURSEID" PRIMARY KEY ("COURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_COURSE" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_COURSE" MODIFY ("COURSENAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_COURSE" MODIFY ("SCHOOLID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_STATISTIC
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" ADD CONSTRAINT "PK_STATS_STATID" PRIMARY KEY ("STATID")
  USING INDEX "PP_ADMIN"."PK_STATS_STATID"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("STATDATE" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("STUDENTNO" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("LEADERNO" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("BKDSESSIONSNO" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("HOURSNO" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("ICT" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("BUSINESS" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("ENGINEERING" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("WEBMEDIA" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("VISUALDESIGN" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("LOGISTICS" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_STATISTIC" MODIFY ("OTHER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_APPLICATIONSTATUS
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONSTATUS" MODIFY ("STATUSNAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONSTATUS" MODIFY ("STATUSDESC" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONSTATUS" ADD CONSTRAINT "PK_APPLICATIONSTATUS_STATUSID" PRIMARY KEY ("STATUSID")
  USING INDEX "PP_ADMIN"."PK_APPLICATIONSTATUS_STATUSID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_AUDIT
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_AUDIT" ADD CONSTRAINT "PK_AUDIT_AUDITID" PRIMARY KEY ("AUDITID")
  USING INDEX "PP_ADMIN"."PK_AUDIT_AUDITID"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_AUDIT" MODIFY ("CHANGETYPE" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_AUDIT" MODIFY ("ENTITYNAME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_AUDIT" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_AUDIT" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_SLOT
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_SLOT" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SLOT" ADD CONSTRAINT "PK_SLOT_SLOTID" PRIMARY KEY ("SLOTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_SLOT" MODIFY ("SLOTID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_SLOT" MODIFY ("LEADERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_USER
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_USER" ADD CONSTRAINT "PK_USER_USERID" PRIMARY KEY ("USERID")
  USING INDEX "PP_ADMIN"."PK_USER_USERID"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_USER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_USER" MODIFY ("ROLEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_APPLICATION
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_APPLICATION" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATION" MODIFY ("NOTE" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATION" MODIFY ("APLCSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATION" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_APPLICATION" ADD CONSTRAINT "PK_APPLICATION_APPLICATIONID" PRIMARY KEY ("APPLICATIONID")
  USING INDEX "PP_ADMIN"."PK_APPLICATION_APPLICATIONID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PP_BOOKING
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKING" ADD CONSTRAINT "PK_BOOKING_BOOKINGID" PRIMARY KEY ("BOOKINGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" MODIFY ("DATEBOOKED" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" MODIFY ("ISONLINE" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" MODIFY ("BOOKINGDATE" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" MODIFY ("TYPEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PP_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_NOTIFICATION" ADD CONSTRAINT "PK_PP_NOTIFICATION_NOTEID" PRIMARY KEY ("NOTFICID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_NOTIFICATION" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_NOTIFICATION" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_NOTIFICATION" MODIFY ("NOTFICMSG" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_NOTIFICATION" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "PP_ADMIN"."PP_NOTIFICATION" MODIFY ("SEEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PP_APPLICATION
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_APPLICATION" ADD CONSTRAINT "FK_PP_APPLICATION_PP_USER" FOREIGN KEY ("STUDENTID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_APPLICATION" ADD CONSTRAINT "FK_APPLICATION_STATUS" FOREIGN KEY ("APLCSTATUSID")
	  REFERENCES "PP_ADMIN"."PP_APPLICATIONSTATUS" ("STATUSID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_APPLICATIONNOTE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" ADD CONSTRAINT "FK_PP_APPLICATIONNOTE_PP_USER" FOREIGN KEY ("USERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_APPLICATIONNOTE" ADD CONSTRAINT "FK_PP_APPLICATIONNOTE" FOREIGN KEY ("APPLICATIONID")
	  REFERENCES "PP_ADMIN"."PP_APPLICATION" ("APPLICATIONID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_AUDIT
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_AUDIT" ADD CONSTRAINT "FK_PP_AUDIT_PP_USER_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_BOOKING
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKING" ADD CONSTRAINT "FK_BOOKING_BOOKINGSTATUS" FOREIGN KEY ("STATUSID")
	  REFERENCES "PP_ADMIN"."PP_BOOKINGSTATUS" ("STATUSID") ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" ADD CONSTRAINT "FK_PP_BOOKING_PP_COURSE" FOREIGN KEY ("COURSEID")
	  REFERENCES "PP_ADMIN"."PP_COURSE" ("COURSEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" ADD CONSTRAINT "FK_PP_BOOKING_PP_SLOT_SLOTID" FOREIGN KEY ("SLOTID")
	  REFERENCES "PP_ADMIN"."PP_SLOT" ("SLOTID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" ADD CONSTRAINT "FK_PP_BOOKING_PP_BOOKINGTYPE" FOREIGN KEY ("TYPEID")
	  REFERENCES "PP_ADMIN"."PP_BOOKINGTYPE" ("TYPEID") ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_BOOKING" ADD CONSTRAINT "FK_PP_BOOKING_PP_USER_USERID" FOREIGN KEY ("STUDENTID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_BOOKINGMEMBER
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" ADD CONSTRAINT "FK_PP_BOOKINGMEMBER" FOREIGN KEY ("STUDENTID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGMEMBER" ADD CONSTRAINT "FK_PP_BOOKINGMEMBER_PP_BOOKING" FOREIGN KEY ("BOOKINGID")
	  REFERENCES "PP_ADMIN"."PP_BOOKING" ("BOOKINGID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_BOOKINGNOTE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_BOOKINGNOTE" ADD CONSTRAINT "FK_PP_BOOKINGNOTE_PP_USER" FOREIGN KEY ("USERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_BOOKINGNOTE" ADD CONSTRAINT "FK_PP_BOOKINGNOTE_PP_BOOKING" FOREIGN KEY ("BOOKINGID")
	  REFERENCES "PP_ADMIN"."PP_BOOKING" ("BOOKINGID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_COURSE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_COURSE" ADD CONSTRAINT "FK_PP_COURSE_PP_SCHOOL_SCHOOLID" FOREIGN KEY ("SCHOOLID")
	  REFERENCES "PP_ADMIN"."PP_SCHOOL" ("SCHOOLID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_LOG
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_LOG" ADD CONSTRAINT "FK_PP_LOG_PP_USER_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_NOTIFICATION" ADD CONSTRAINT "FK_PP_NOTIFICATION_PP_USER" FOREIGN KEY ("USERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_OFFEREDCOURSE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_OFFEREDCOURSE" ADD CONSTRAINT "FK_PP_OFFEREDCOURSE_PP_USER" FOREIGN KEY ("LEADERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_OFFEREDCOURSE" ADD CONSTRAINT "FK_PP_OFFEREDCOURSE_PP_COURSE" FOREIGN KEY ("COURSEID")
	  REFERENCES "PP_ADMIN"."PP_COURSE" ("COURSEID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_RECOMMENDATION
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" ADD CONSTRAINT "FK_PP_RECOMMENDATION_PP_USER" FOREIGN KEY ("STUDENTID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" ADD CONSTRAINT "FK_PP_RECOMMENDATION_PP_TUTOR" FOREIGN KEY ("TUTORID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_RECOMMENDATION" ADD CONSTRAINT "FK_RECOMMENDATION_STATUS" FOREIGN KEY ("STATUSID")
	  REFERENCES "PP_ADMIN"."PP_RECSTATUS" ("STATUSID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" ADD CONSTRAINT "FK_PP_SCHEDULE_PP_USER_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_DAY" FOREIGN KEY ("DAYID")
	  REFERENCES "PP_ADMIN"."PP_DAY" ("DAYID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_SLOT
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_SLOT" ADD CONSTRAINT "FK_PP_SLOT_PP_SLOTTYPE_TYPEID" FOREIGN KEY ("TYPEID")
	  REFERENCES "PP_ADMIN"."PP_SLOTTYPE" ("TYPEID") ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_SLOT" ADD CONSTRAINT "FK_PP_SLOT_PP_USER_USERID" FOREIGN KEY ("LEADERID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PP_ADMIN"."PP_SLOT" ADD CONSTRAINT "FK_SLOT_DAY" FOREIGN KEY ("DAYID")
	  REFERENCES "PP_ADMIN"."PP_DAY" ("DAYID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_TRANSCRIPT
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_TRANSCRIPT" ADD CONSTRAINT "FK_PP_TRANSCRIPT_PP_USER_USERID" FOREIGN KEY ("STUDENTID")
	  REFERENCES "PP_ADMIN"."PP_USER" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PP_USER
--------------------------------------------------------

  ALTER TABLE "PP_ADMIN"."PP_USER" ADD CONSTRAINT "FK_PP_USER_PP_ROLE_ROLEID" FOREIGN KEY ("ROLEID")
	  REFERENCES "PP_ADMIN"."PP_ROLE" ("ROLEID") ON DELETE CASCADE ENABLE;
